const speakerImages = {
  placeholder: require('assets/images/speakers/holo/placeholder.png'),
  'adam-kowalczyk.jpg': require('assets/images/speakers/adam-kowalczyk.jpg'),
  'ania-kowalczyk.jpg': require('assets/images/speakers/ania-kowalczyk.jpg'),
  'daria-marciniak.jpg': require('assets/images/speakers/daria-marciniak.jpg'),
  'dominik-tomaszewski.jpg': require('assets/images/speakers/dominik-tomaszewski.jpg'),
  'gosia-tomaszewska.jpg': require('assets/images/speakers/gosia-tomaszewska.jpg'),
  'jacek-gromadzki.jpg': require('assets/images/speakers/jacek-gromadzki.jpg'),
  'katarzyna-augustyniak.jpg': require('assets/images/speakers/katarzyna-augustyniak.jpg'),
  'krzysztof-persona.jpg': require('assets/images/speakers/krzysztof-persona.jpg'),
  'kuba-kuzynin.jpg': require('assets/images/speakers/kuba-kuzynin.jpg'),
  'kuba-marciniak.jpg': require('assets/images/speakers/kuba-marciniak.jpg'),
  'luiz-f-cardoso.jpg': require('assets/images/speakers/luiz-f-cardoso.jpg'),
  'lukasz-konieczny.jpg': require('assets/images/speakers/lukasz-konieczny.jpg'),
  'malgorzata-bieniaszewska.jpg': require('assets/images/speakers/malgorzata-bieniaszewska.jpg'),
  'marcin-lindner.jpg': require('assets/images/speakers/marcin-lindner.jpg'),
  'maria-perenc.jpg': require('assets/images/speakers/maria-perenc.jpg'),
  'marysia-lindner.jpg': require('assets/images/speakers/marysia-lindner.jpg'),
  'mateusz-chowaniec.jpg': require('assets/images/speakers/mateusz-chowaniec.jpg'),
  'ola-konieczna.jpg': require('assets/images/speakers/ola-konieczna.jpg'),
  'paulina-kuzynin.jpg': require('assets/images/speakers/paulina-kuzynin.jpg'),
  'revolutionary-art.jpg': require('assets/images/speakers/revolutionary-art.jpg'),
  'ryszard-augustyniak.jpg': require('assets/images/speakers/ryszard-augustyniak.jpg'),
  'serhii-makhiboroda.jpg': require('assets/images/speakers/serhii-makhiboroda.jpg'),
  'szymon-perenc.jpg': require('assets/images/speakers/szymon-perenc.jpg'),
  'zbyszek-zarozny.jpg': require('assets/images/speakers/zbyszek-zarozny.jpg'),
}

export default speakerImages
